# Generated by Django 4.1.2 on 2022-11-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='total_love',
        ),
        migrations.RemoveField(
            model_name='car',
            name='total_review',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='time_buy',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
