# Generated by Django 4.1.2 on 2022-11-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_car_is_reviewed_car_total_love_car_total_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='car',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='total_love',
        ),
        migrations.RemoveField(
            model_name='car',
            name='total_review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
