# Generated by Django 4.1.3 on 2022-11-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_alter_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='link_buy',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
