# Generated by Django 4.1.2 on 2022-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_contributor',
            field=models.BooleanField(default=False, help_text='Allow user to create news and catalog', verbose_name='contributor status'),
        ),
    ]
