# Generated by Django 4.1.2 on 2022-10-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evices', '0002_alter_carservice_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='photo',
            field=models.ImageField(upload_to='evices/images'),
        ),
    ]
