# Generated by Django 4.1.2 on 2022-10-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evices', '0003_alter_carservice_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='photo',
            field=models.URLField(),
        ),
    ]
