# Generated by Django 4.1.2 on 2022-10-31 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evices', '0004_alter_carservice_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='link_gmap',
            field=models.URLField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carservice',
            name='time_close',
            field=models.TimeField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carservice',
            name='time_open',
            field=models.TimeField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
