# Generated by Django 4.1.2 on 2022-10-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evices', '0005_carservice_link_gmap_carservice_time_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='time_close',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
    ]
