# Generated by Django 4.1.2 on 2022-10-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evices', '0006_alter_carservice_time_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carservice',
            name='time_open',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
    ]
