# Generated by Django 4.1 on 2022-12-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('photo', models.URLField()),
                ('time_open', models.TimeField(blank=True, max_length=200, null=True)),
                ('time_close', models.TimeField(blank=True, max_length=200, null=True)),
                ('link_gmap', models.URLField()),
            ],
        ),
    ]
