# Generated by Django 4.1 on 2022-12-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('photo', models.URLField()),
                ('link_buy', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='CarService',
        ),
    ]
